### Getting started

In [1]:
import numpy as np
import torch

### 4 Tensors

In [7]:
# 1.
x = torch.Tensor(5,3) # values from 0 to 1
print(x)
print(x.type)
# 2.
y = torch.rand(5,3) # values from 0 to 1
print(y)
print(y.type)
y = torch.randn(5,3) # values from -1 to 1

tensor([[ 1.4013e-45,  0.0000e+00, -1.3443e+33],
        [ 3.0708e-41,  3.9236e-44,  3.0708e-41],
        [-3.7575e+35,  4.5636e-41,  2.8026e-45],
        [ 3.0708e-41, -1.3446e+33,  3.0708e-41],
        [ 2.8026e-45,  0.0000e+00,  3.9236e-44]])
<built-in method type of Tensor object at 0x7f3721d05708>
tensor([[0.4629, 0.6055, 0.9941],
        [0.9931, 0.4755, 0.5331],
        [0.3602, 0.2784, 0.7800],
        [0.2182, 0.4734, 0.9141],
        [0.8809, 0.5033, 0.2096]])
<built-in method type of Tensor object at 0x7f37f4b105e8>


In [18]:
# 3.
x = x.double()
y = y.double()
print(x)
print(y)
# 4.
x = torch.Tensor([[-0.1859, 1.3970, 0.5236],
[ 2.3854, 0.0707, 2.1970],
[-0.3587, 1.2359, 1.8951],
[-0.1189, -0.1376, 0.4647],
[-1.8968, 2.0164, 0.1092]])
y = torch.Tensor([[ 0.4838, 0.5822, 0.2755],
[ 1.0982, 0.4932, -0.6680],
[ 0.7915, 0.6580, -0.5819],
[ 0.3825, -1.1822, 1.5217],
[ 0.6042, -0.2280, 1.3210]])
print(x.shape)
print(y.shape)
# 5.
z = torch.stack((x,y))
print(z.shape)
z1 = torch.cat((x,y), 0)
print(z1.shape)
z2 = torch.cat((x,y), 1)
print(z2.shape)
# 6.
print(y[4,2])
print(z[1,4,2])
# 7.
print(z[:,4,2])

tensor([[-0.1859,  1.3970,  0.5236],
        [ 2.3854,  0.0707,  2.1970],
        [-0.3587,  1.2359,  1.8951],
        [-0.1189, -0.1376,  0.4647],
        [-1.8968,  2.0164,  0.1092]], dtype=torch.float64)
tensor([[ 0.4838,  0.5822,  0.2755],
        [ 1.0982,  0.4932, -0.6680],
        [ 0.7915,  0.6580, -0.5819],
        [ 0.3825, -1.1822,  1.5217],
        [ 0.6042, -0.2280,  1.3210]], dtype=torch.float64)
torch.Size([5, 3])
torch.Size([5, 3])
torch.Size([2, 5, 3])
torch.Size([10, 3])
torch.Size([5, 6])
tensor(1.3210)
tensor(1.3210)
tensor([0.1092, 1.3210])


In [21]:
# 8.
print(x+y)
print(torch.add(x,y))
print(x.add(y))
torch.add(x,y,out=x)
print(x)
# 9.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

tensor([[ 0.7817,  2.5614,  1.0746],
        [ 4.5818,  1.0571,  0.8610],
        [ 1.2243,  2.5519,  0.7313],
        [ 0.6461, -2.5020,  3.5081],
        [-0.6884,  1.5604,  2.7512]])
tensor([[ 0.7817,  2.5614,  1.0746],
        [ 4.5818,  1.0571,  0.8610],
        [ 1.2243,  2.5519,  0.7313],
        [ 0.6461, -2.5020,  3.5081],
        [-0.6884,  1.5604,  2.7512]])
tensor([[ 0.7817,  2.5614,  1.0746],
        [ 4.5818,  1.0571,  0.8610],
        [ 1.2243,  2.5519,  0.7313],
        [ 0.6461, -2.5020,  3.5081],
        [-0.6884,  1.5604,  2.7512]])
tensor([[ 0.7817,  2.5614,  1.0746],
        [ 4.5818,  1.0571,  0.8610],
        [ 1.2243,  2.5519,  0.7313],
        [ 0.6461, -2.5020,  3.5081],
        [-0.6884,  1.5604,  2.7512]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
# 10.
x = torch.rand(10,10)
y = torch.rand(2,100)
xR = torch.reshape(x,[1,100])
yR = torch.reshape(y,[100,2])
print(torch.mm(xR,yR))

tensor([[22.8065, 25.1728]])


### 5 NumPy and PyTorch

In [33]:
# 11.
a = torch.ones(5)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))
# 12.
a[0] += 1
print(a)
print(b)
# 13.
a.add_(1)
print(a)
print(b)
a[:] += 1
print(a)
print(b)
a = a.add(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 1., 1., 1., 1.])
[2. 1. 1. 1. 1.]
tensor([3., 2., 2., 2., 2.])
[3. 2. 2. 2. 2.]
tensor([4., 3., 3., 3., 3.])
[4. 3. 3. 3. 3.]
tensor([5., 4., 4., 4., 4.])
[4. 3. 3. 3. 3.]


In [37]:
# 14.
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
# 15.
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
start1 = time.time()
x = torch.randn(5, 3).to(device)
end1 = time.time()
print(end1 - start1)
start2 = time.time()
y = torch.randn(5, 3, device=device)
end2 = time.time()
print(end2 - start2)
z = x + y
# 16.
print(z.cpu().numpy())
print(z.numpy())

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
cuda
0.014699697494506836
0.00024628639221191406
[[-1.8749033  -0.9573189   1.1539512 ]
 [-0.48497128  0.7178381  -0.13138461]
 [-0.05684379 -0.6167562   1.8247457 ]
 [ 0.13982892  0.60104454 -0.61274654]
 [ 0.07626495 -1.1959951  -0.02312876]]


TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### 6 Autograd: automatic differentiation

In [51]:
# 17.
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
# 18.
z = y * y * 3
f = z.mean()
print(z, f)
# 19.
f.backward() # That's it!
x.grad

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

### 7 MNIST Data preparation

In [67]:
# 21.
import MNISTtools
xtrain, ltrain = MNISTtools.load(dataset="training", path="./mnist/")
xtest, ltest = MNISTtools.load(dataset="testing", path="./mnist/")
print('xtrain shape:',xtrain.shape)
print('ltrain shape:',ltrain.shape)
print('xtest shape:',xtest.shape)
print('ltest shape:',ltest.shape)

# normalize values from -1 to 1
def normalize_MNIST_images(x):
    normalized = (x-255/2)/(255/2)
    normalized = normalized.astype(np.float32)
    return(normalized)
    
xtrain = normalize_MNIST_images(xtrain)
xtest = normalize_MNIST_images(xtest)
# 22.
xtrain = np.reshape(xtrain, [28,28,1,60000])
xtest = np.reshape(xtest, [28,28,1,10000])
print('xtrain shape:',xtrain.shape)
print('ltrain shape:',ltrain.shape)
print('xtest shape:',xtest.shape)
print('ltest shape:',ltest.shape)
bathSize = 1
numInputChannels = 1
imageHeight = xtrain[:,:,:,0].shape[0]
imageWidth = xtrain[:,:,:,0].shape[1]

xtrain shape: (784, 60000)
ltrain shape: (60000,)
xtest shape: (784, 10000)
ltest shape: (10000,)
xtrain shape: (28, 28, 1, 60000)
ltrain shape: (60000,)
xtest shape: (28, 28, 1, 10000)
ltest shape: (10000,)


In [69]:
# 23.
MNISTtools.show(xtrain[42, 0, :, :])
# 24.
xtrain = torch.from_numpy(xtrain)
ltrain = torch.from_numpy(ltrain)
xtest = torch.from_numpy(xtest)
ltest = torch.from_numpy(ltest)

IndexError: index 42 is out of bounds for axis 0 with size 28

### Convolutional Neural Network (CNN) for MNIST classification

In [ ]:
# 26.
import torch.nn as nn
import torch.nn.functional as F

# This is our neural networks class that inherits from nn.Module
class LeNet(nn.Module):
    
    # Here we define our network structure
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(1, 16, 5)
        self.fc1 = nn.Linear(16, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    # Here we define one forward pass through the network
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = COMPLETE
        x = x.view(-1, self.num_flat_features(x))
        x = COMPLETE
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    # Determine the number of features in a batch of tensors
    def num_flat_features(self, x ):
        size = x.size()[1:]
        return np.prod(size)
    
net = LeNet()
print(net)
