In [10]:
print('HelloWorld!')

HelloWorld!


# 2 Numpy

### 2.1 Arrays

In [16]:
# 1.
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5

<class 'numpy.ndarray'>
(3,)
1 2 3


In [20]:
# 2.
b = np.array([[1,2,3], [4,5,6]])
print(np.rank(b))
print(b.shape)
print(b[0,0])
print(b[0,1])
print(b[1,0])

2
(2, 3)
1
2
4


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  after removing the cwd from sys.path.


In [21]:
# 3.
a = np.zeros((2,2)) # an array of all zeros
b = np.ones((1,2)) # an array of all ones
c = np.full((2,2), 7) # a constant array
d = np.eye(2) # a 2x2 identity matrix
e = np.random.random((2,2)) # an array filled with random values

### 2.2 Array indexing

In [28]:
# 4.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a.shape)
print(b.shape)
# Shape of a = (3,4)
# Shape of b = (2,2)

(3, 4)
(2, 2)


In [29]:
# 5.
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
# The last line prints 77
# Modifying b modifies the original array

2
77


In [33]:
# 6.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :] # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [34]:
# 7.
a = np.array([[1,2], [3,4], [5,6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1,1], a[2, 0]]))
# The 2 arrays are equivalent

[1 4 5]
[1 4 5]


In [35]:
# 8.
b = a[[0, 0], [1, 1]]
c = np.array([a[0, 1], a[0, 1]])

In [37]:
# 9.
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b = np.array([0,2,0,1])
print(a[np.arange(4), b]) # prints a values of each row at b index
a[np.arange(4),b] += 10 # same as above, but adds 10 to a values
print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [41]:
# 10.
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2)
print(a[bool_idx])
print(a[a > 2])
# Values of a greater than 2 are printed as a vector

[3 4 5 6]
[3 4 5 6]


### 2.3 Datatypes

In [42]:
# 11.
x = np.array([1,2]) # let numpy choose the datatype
print(x.dtype)

y = np.array([1.0,2.0]) # let numpy choose the datatype
print(y.dtype)

z = np.array([1,2], dtype=np.int32) # let numpy choose the datatype
print(z.dtype)

int64
float64
int32


### 2.4 Array math

In [43]:
# 12.
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [44]:
# 13. 
# dot - matrix multiplication
v = np.array([9,10])
w = np.array([11,12])
print(v.dot(w))
print(np.dot(v,w))

219
219


In [45]:
# 14.
x = np.array([[1,2],[3,4]])
print(x.dot(v))
print(np.dot(x,v))

[29 67]
[29 67]


In [49]:
# 15.
y = np.array([[5,6,7],[7,8,9]])
print(np.dot(x,y))

x = np.array([[1,2],[3,4]])
print(np.sum(x)) # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0)) # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1)) # Compute sum of each row; prints "[3 7]"

[[19 22 25]
 [43 50 57]]
10
[4 6]
[3 7]


In [51]:
# 16.
# transpose a matrix
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(x.T)

[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


### 2.5 Broadcasting

In [76]:
# 17.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)

for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = x[i,j] + v[j]
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [74]:
# 18.
vv = np.tile(v, (4, 1))
print(vv)
# compute y from x and vv
y = np.add(x,vv)
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [86]:
# 19.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v # Add v to each row of x using broadcasting
print(y)
v = np.array([1,2,3])
w = np.array([4,5])
#v = np.reshape(v, (3,1))
u = np.outer(v,w)
print(u)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [88]:
# 20.
x = np.array([[1,2,3],[4,5,6]])
s = x + v
print(s)

[[2 4 6]
 [5 7 9]]


In [89]:
# 21.
r = x + w
print(w)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 